# Generated by Django 5.1.6 on 2025-05-11 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_verbose_names'),
        ('car', '0002'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобіль', 'verbose_name_plural': 'Автомобілі'},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='model',
        ),
        migrations.AlterField(
            model_name='car',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='Покупець'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car/media/uploads', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Місцезнаходження'),
        ),
        migrations.AlterField(
            model_name='car',
            name='milage',
            field=models.PositiveIntegerField(default=0, verbose_name='Пробіг (км)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=0, verbose_name='Рік випуску'),
        ),
    ]
